---
- name: Install google authenticator
  ansible.builtin.package:
    name: google-authenticator
    state: present

- name: Add SSH configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "{{ item} }"
  with_items:
    - "UsePAM yes"
    - "ChallengeResponseAuthentication yes"
    - "UseDNS no"

- name: Add google-authenticator to pam.d/sshd
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    insertafter: "auth."
    firstmatch: "yes"
    line: "auth       required     pam_google_authenticator.so nullok"
