---
- name: Install requisite packages for domain authenticaition
  yum:
    name:
    - "epel-release"
    - "sssd"
    - "oddjob"
    - "oddjob-mkhomedir"
    - "adcli"
    - "realmd"
    state: latest

- name: Join the machine to the domain
  ansible.builtin.shell: "echo {{domain_admin_password}} | realm join --user={{domain_admin}} {{domain_controller_fqdn}}"
  notify:
    - restart sssd
    - restart sshd

- name: enable services
  ansible.builtin.service:
    name: "{{item}}"
    status: enabled
  with_items:
    - "realmd"
    - "sssd"

- name: configure sudoer groups
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/domain_groups
    line: "%{{item}} ALL=(ALL) NOPASSWD: ALL"
  with_items:
    - sudoers_groups

- name: configure groups permitted to access the machine
  shell: "realm permit -g {{permitted_groups}}"
  notify:
    - restart sssd
