---
# handlers file for Linux_SSSD

- name: restart sssd
  ansible.builtin.service:
    name: sssd
    state: restarted

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
